version: "3.7"
services:
  database:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  webserver:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    image: php-8
    container_name: php8
    restart: unless-stopped
    volumes:
      - ./app:/var/www
    environment:
      - ENV_AMBIENTE=dev
      - PHP_DISPLAY_ERRORS=On
      - PHP_ERROR_REPORTING=E_ALL & ~E_NOTICE
    depends_on:
      - webserver
      - database
    links:
      - webserver
      - database
volumes:
  database:
    driver: local
